
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 152
#define YY_END_OF_BUFFER 153
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[492] =
    {   0,
        0,    0,    0,    0,  153,  151,    8,    5,  111,  151,
        7,  107,  122,  151,  125,  126,  105,  103,  127,  104,
      112,  106,  145,  145,  131,  128,  110,  108,  109,   98,
      149,  149,  149,  149,  149,  149,  149,  149,  149,  132,
      133,  124,  149,  149,  149,  149,  149,  149,  149,  149,
      149,  149,  149,  149,  149,  149,  149,  149,  149,  129,
      123,  130,  114,    3,    4,    3,    8,   95,   92,    0,
        0,  147,    0,    7,   93,  117,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   85,  101,   86,  102,  100,
        1,    6,    0,  145,  145,  150,  150,  115,   90,   91,

       89,  116,   96,   97,  149,  149,  149,  149,  149,  149,
      149,  149,  149,  149,  149,  119,  149,  149,  149,   28,
      149,   40,  149,  149,  149,  149,  149,  149,   11,  149,
      149,  149,  149,  149,  149,  149,  149,  149,   16,  149,
       17,   31,   84,  149,  149,  149,  149,  149,  149,  149,
      149,  149,  149,  149,  149,  149,  149,  149,  149,  149,
      149,  118,   94,    2,   88,   26,   27,  147,    0,  144,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   99,
        0,    6,  146,  150,  145,  121,   87,  120,  149,  149,
      149,  149,  149,  149,  136,  149,  149,  149,  149,  149,

      149,   29,  149,  149,  149,  149,  149,  149,  149,  149,
      149,  149,  149,  149,  149,  149,  149,  149,  149,   14,
       15,   48,  149,  149,  149,  149,  149,  149,  149,  149,
      149,  149,  149,   75,  149,  149,  149,  149,  149,  149,
      149,  149,  149,   53,  149,  149,  149,  149,  149,  149,
       37,  149,   21,   22,  149,  149,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,  149,
      149,  134,  142,  149,  149,  137,  149,  149,  149,  149,
      149,  149,  149,  149,  149,  149,  149,  149,   62,  149,
      149,   12,   63,  149,  149,  149,  149,   46,  149,  149,

      149,   49,  149,  149,  149,  149,  149,   18,  149,   73,
      149,  149,  149,  149,  149,  149,  149,  149,  149,  149,
      149,  149,  149,  149,  149,   35,  149,   20,  149,  149,
      149,   23,  149,  149,    0,    0,    0,    0,  113,    0,
        0,    6,  143,  149,  149,  138,  135,  149,  149,  149,
      149,    9,   41,   30,  149,  149,  149,  149,  149,  149,
      149,  149,   13,   45,   66,  149,   67,  149,   69,  149,
      149,  149,  149,  149,  149,   50,  149,  149,  149,  149,
      149,  149,  149,  149,  149,   34,  149,  149,   36,  149,
      149,   55,  149,   56,   24,  148,    0,    0,    0,  149,

      139,  141,  149,   58,  149,  149,  149,  149,  149,  149,
      149,   64,  149,  149,   25,   68,  149,  149,  149,   32,
      149,  149,  149,  149,  149,   78,  149,  149,   19,   80,
      149,  149,  149,  149,   39,   83,    0,  140,  149,  149,
      149,  149,  149,  149,  149,   44,  149,   47,  149,  149,
      149,  149,   33,   76,  149,  149,  149,   79,  149,   81,
       82,  149,   57,  149,  149,  149,   10,  149,   43,   65,
       70,   71,   72,   74,   51,  149,   52,   54,  149,  149,
       60,  149,  149,   77,   38,   59,  149,  149,   42,   61,
        0

    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   21,   22,   23,
       24,   25,   26,    1,   27,   28,   29,   30,   31,   32,
       33,   33,   34,   33,   33,   35,   33,   33,   33,   33,
       33,   33,   36,   33,   33,   33,   33,   37,   33,   33,
       38,   39,   40,   41,   33,    1,   42,   43,   44,   45,

       46,   47,   48,   49,   50,   51,   52,   53,   54,   55,
       56,   57,   33,   58,   59,   60,   61,   62,   63,   64,
       65,   33,   66,   67,   68,   69,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[70] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    3,
        1,    1,    1,    1,    1,    1,    4,    1,    5,    5,
        1,    1,    1,    1,    1,    1,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    1,    1,    1,
        1,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[502] =
    {   0,
        0,    0,   67,   68,  571,  572,  568,  572,   68,   68,
        0,  572,   65,  530,   65,  572,  572,   61,  572,   60,
      551,   64,   71,   85,  572,  572,   55,  543,   62,   89,
      508,   47,  516,  508,    0,  510,  507,  505,   49,  572,
      572,  536,   70,   57,   74,   75,   73,   91,  513,   89,
      516,   63,   77,   81,  511,   50,  104,  514,  506,  572,
      121,  572,  572,  572,  572,  536,  551,  572,  528,   95,
      146,  546,    0,    0,  572,  572,  540,  151,   99,  500,
      492,  494,  491,  489,  108,  572,  572,  572,  572,  521,
        0,    0,  140,  146,  154,    0,  193,  519,  572,  518,

      572,  517,  572,  572,    0,  482,  483,  478,  495,  475,
      479,  474,  478,  476,  473,  572,  471,  469,  473,  501,
      480,    0,  465,  482,  121,  467,  462,  468,    0,  465,
      460,  457,  120,  464,  126,  458,  460,  454,    0,  456,
      136,    0,    0,  452,  461,  457,  458,  462,  447,  134,
      137,  463,  154,  140,  138,  455,  149,  140,  447,  150,
      169,  572,  572,  572,  572,  572,  572,  572,  179,  572,
      447,  442,  459,  439,  443,  438,  442,  440,  437,  572,
      481,    0,  197,    0,    0,  572,  572,  572,  451,  439,
      445,  432,  446,  446,    0,  439,  428,  435,  424,  422,

      426,  572,  439,  436,  420,  421,  167,  418,  434,  429,
      432,  427,  418,  425,  424,  410,  415,  421,  424,    0,
        0,    0,  409,  414,  403,  412,  415,  414,  413,  403,
      404,  410,  173,    0,  403,  412,  391,  172,  399,  405,
      403,  388,  395,  390,  400,  388,  391,  384,  386,  395,
        0,  394,  378,  396,  175,  384,  205,  431,  432,  381,
      387,  374,  388,  388,  417,  380,  369,  376,  407,  359,
      377,    0,    0,  369,  361,    0,  360,  364,  360,  375,
      356,  363,  365,  354,  370,  351,  360,  350,    0,  360,
      353,    0,    0,  362,  347,  358,  358,    0,  349,  343,

      336,    0,  344,  340,  339,  346,  342,    0,  350,    0,
      351,  350,  337,  348,  343,  342,  337,  336,  335,  326,
      337,  340,  323,  334,  321,    0,  315,    0,  192,  331,
      318,    0,  329,  328,  368,  326,  318,  310,  572,  309,
      313,  572,    0,  325,  320,    0,    0,  317,  322,  310,
      320,    0,    0,    0,  306,  302,  304,  308,  315,  306,
      295,  299,    0,    0,  300,  292,    0,  305,    0,  295,
      294,  298,  287,  286,  297,    0,  284,  285,  298,  297,
      278,  293,  283,  292,  278,    0,  280,  288,    0,  280,
      285,    0,  283,    0,    0,  572,  288,  283,  280,  272,

        0,    0,  282,    0,  265,  274,  262,  261,  266,  260,
      275,    0,  276,  252,    0,    0,  274,  265,  259,    0,
      257,  266,  265,  250,  249,    0,  262,  262,    0,    0,
      264,  260,  260,  253,    0,    0,  247,    0,  241,  250,
      243,  254,  251,  243,  249,    0,  241,    0,  240,  232,
      245,  232,    0,    0,  224,  242,  229,    0,  232,    0,
        0,  235,    0,  216,  211,  200,    0,  205,    0,    0,
        0,    0,    0,    0,    0,  202,    0,    0,  187,  190,
        0,  187,  187,    0,    0,    0,  183,  156,    0,    0,
      572,  248,  253,  258,  263,  265,  162,  270,  275,   78,

      280
    } ;

static const flex_int16_t yy_def[502] =
    {   0,
      491,    1,  492,  492,  491,  491,  491,  491,  491,  493,
      494,  491,  491,  495,  491,  491,  491,  491,  491,  491,
      491,  491,  496,  496,  491,  491,  491,  491,  491,  491,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  491,
      491,  491,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  491,
      491,  491,  491,  491,  491,  491,  491,  491,  491,  491,
      493,  491,  493,  494,  491,  491,  491,  491,  491,  491,
      491,  491,  491,  491,  491,  491,  491,  491,  491,  491,
      498,  499,  491,  496,  496,  500,  500,  491,  491,  491,

      491,  491,  491,  491,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  491,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  491,  491,  491,  491,  491,  491,  491,  501,  491,
      491,  491,  491,  491,  491,  491,  491,  491,  491,  491,
      491,  499,  491,  500,   97,  491,  491,  491,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,

      497,  491,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  501,  491,  501,  491,
      491,  491,  491,  491,  491,  491,  491,  491,  491,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,

      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  491,  491,  491,  491,  491,  491,
      491,  491,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  491,  491,  491,  491,  497,

      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  491,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
        0,  491,  491,  491,  491,  491,  491,  491,  491,  491,

      491
    } ;

static const flex_int16_t yy_nxt[642] =
    {   0,
        6,    7,    8,    9,   10,   11,    6,   12,   13,   14,
       15,   16,   17,   18,   19,   20,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   30,   31,   32,   33,   34,
       35,   36,   35,   37,   38,   39,   35,   40,    6,   41,
       42,   43,   44,   45,   46,   47,   48,   49,   35,   50,
       35,   35,   51,   35,   52,   53,   54,   55,   56,   57,
       35,   58,   59,   35,   35,   60,   61,   62,   63,   65,
       65,   68,   72,   75,   86,   88,   91,   98,   99,   66,
       66,   92,  184,   89,   87,  101,  102,   93,   76,   94,
       95,   69,   79,   80,   81,  154,   82,  114,   83,   84,

       85,   93,  107,   94,   95,  103,   73,   97,  115,  104,
      155,  108,  117,  118,  121,  123,  127,   70,  145,  147,
      128,  122,  150,  146,  119,  131,  124,  132,  120,  125,
      129,  126,  134,  148,   97,  139,  133,  149,  151,  130,
      135,  152,  140,  141,  162,  156,  136,  142,  143,  166,
      168,  137,  157,  167,  171,   77,  178,   77,  183,  183,
       77,  158,   93,  172,   94,   95,  105,  179,  159,   77,
       93,  217,   94,   95,  206,  207,  214,  235,  218,  215,
      219,  243,  224,  258,   73,  225,  237,  163,  226,   77,
      227,  236,  238,   77,  245,  228,  246,  240,  248,  244,

      250,  490,  253,  241,  251,   77,  249,  254,   77,  258,
       77,  185,  185,  242,  255,  183,  183,  259,  256,  185,
      185,  185,  185,  185,  185,  286,  287,  310,  315,  332,
      311,  316,  333,  390,  185,  185,  185,  185,  185,  185,
      489,  488,  487,  259,  486,  485,  484,  391,   64,   64,
       64,   64,   64,   71,  483,   71,   71,   71,   74,  482,
       74,   74,   74,   77,   77,  481,   77,   77,   96,   96,
      181,  480,  181,  181,  181,  182,  479,  182,  182,  182,
      257,  257,  257,  257,  257,  478,  477,  476,  475,  474,
      473,  472,  471,  470,  469,  468,  467,  466,  465,  464,

      463,  265,  462,  461,  460,  459,  458,  457,  456,  455,
      454,  453,  452,  451,  450,  449,  448,  447,  446,  445,
      444,  443,  442,  441,  440,  439,  438,  265,  265,  437,
      436,  435,  434,  433,  432,  431,  430,  429,  428,  427,
      426,  425,  424,  423,  422,  421,  420,  419,  418,  417,
      416,  415,  414,  413,  412,  411,  410,  409,  408,  407,
      406,  405,  404,  403,  402,  401,  400,  399,  265,  265,
      398,  397,  396,  395,  394,  393,  392,  389,  388,  387,
      386,  385,  384,  383,  382,  381,  380,  379,  378,  377,
      376,  375,  374,  373,  372,  371,  370,  369,  368,  367,

      366,  365,  364,  363,  362,  361,  360,  359,  358,  357,
      356,  355,  354,  353,  352,  351,  350,  349,  348,  347,
      346,  345,  344,  343,  342,  341,  340,  265,  339,  338,
      337,  265,  265,  336,  491,  335,  334,  331,  330,  329,
      328,  327,  326,  325,  324,  323,  322,  321,  320,  319,
      318,  317,  314,  313,  312,  309,  308,  307,  306,  305,
      304,  303,  302,  301,  300,  299,  298,  297,  296,  295,
      294,  293,  292,  291,  290,  289,  288,  285,  284,  283,
      282,  281,  280,  279,  278,  277,  276,  275,  274,  273,
      272,  271,  270,  269,  268,  267,  266,  265,  264,  263,

      262,  261,  260,  252,  247,  239,  234,  233,  232,  231,
      230,  229,  223,  222,  221,  220,  216,  213,  212,  211,
      210,  209,  208,  205,  204,  203,  202,  201,  200,  199,
      198,  197,  196,  195,  194,  193,  192,  191,  190,  189,
      188,  187,  186,  180,  177,  176,  175,  174,  173,  170,
      169,  165,   67,  164,  161,  160,  153,  144,  138,  116,
      113,  112,  111,  110,  109,  106,  100,   90,   78,   67,
      491,    5,  491,  491,  491,  491,  491,  491,  491,  491,
      491,  491,  491,  491,  491,  491,  491,  491,  491,  491,
      491,  491,  491,  491,  491,  491,  491,  491,  491,  491,

      491,  491,  491,  491,  491,  491,  491,  491,  491,  491,
      491,  491,  491,  491,  491,  491,  491,  491,  491,  491,
      491,  491,  491,  491,  491,  491,  491,  491,  491,  491,
      491,  491,  491,  491,  491,  491,  491,  491,  491,  491,
      491
    } ;

static const flex_int16_t yy_chk[642] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        4,    9,   10,   13,   18,   20,   22,   27,   27,    3,
        4,   22,  500,   20,   18,   29,   29,   23,   13,   23,
       23,    9,   15,   15,   15,   56,   15,   39,   15,   15,

       15,   24,   32,   24,   24,   30,   10,   23,   39,   30,
       56,   32,   43,   43,   44,   45,   46,    9,   52,   53,
       46,   44,   54,   52,   43,   47,   45,   47,   43,   45,
       46,   45,   48,   53,   23,   50,   47,   53,   54,   46,
       48,   54,   50,   50,   61,   57,   48,   50,   50,   70,
       71,   48,   57,   70,   79,   78,   85,   78,   93,   93,
       78,   57,   94,   79,   94,   94,  497,   85,   57,   78,
       95,  135,   95,   95,  125,  125,  133,  150,  135,  133,
      135,  154,  141,  169,   71,  141,  151,   61,  141,   78,
      141,  150,  151,   78,  155,  141,  155,  153,  157,  154,

      158,  488,  160,  153,  158,   78,  157,  160,   78,  257,
       78,   97,   97,  153,  161,  183,  183,  169,  161,   97,
       97,   97,   97,   97,   97,  207,  207,  233,  238,  255,
      233,  238,  255,  329,   97,   97,   97,   97,   97,   97,
      487,  483,  482,  257,  480,  479,  476,  329,  492,  492,
      492,  492,  492,  493,  468,  493,  493,  493,  494,  466,
      494,  494,  494,  495,  495,  465,  495,  495,  496,  496,
      498,  464,  498,  498,  498,  499,  462,  499,  499,  499,
      501,  501,  501,  501,  501,  459,  457,  456,  455,  452,
      451,  450,  449,  447,  445,  444,  443,  442,  441,  440,

      439,  437,  434,  433,  432,  431,  428,  427,  425,  424,
      423,  422,  421,  419,  418,  417,  414,  413,  411,  410,
      409,  408,  407,  406,  405,  403,  400,  399,  398,  397,
      393,  391,  390,  388,  387,  385,  384,  383,  382,  381,
      380,  379,  378,  377,  375,  374,  373,  372,  371,  370,
      368,  366,  365,  362,  361,  360,  359,  358,  357,  356,
      355,  351,  350,  349,  348,  345,  344,  341,  340,  338,
      337,  336,  335,  334,  333,  331,  330,  327,  325,  324,
      323,  322,  321,  320,  319,  318,  317,  316,  315,  314,
      313,  312,  311,  309,  307,  306,  305,  304,  303,  301,

      300,  299,  297,  296,  295,  294,  291,  290,  288,  287,
      286,  285,  284,  283,  282,  281,  280,  279,  278,  277,
      275,  274,  271,  270,  269,  268,  267,  266,  265,  264,
      263,  262,  261,  260,  259,  258,  256,  254,  253,  252,
      250,  249,  248,  247,  246,  245,  244,  243,  242,  241,
      240,  239,  237,  236,  235,  232,  231,  230,  229,  228,
      227,  226,  225,  224,  223,  219,  218,  217,  216,  215,
      214,  213,  212,  211,  210,  209,  208,  206,  205,  204,
      203,  201,  200,  199,  198,  197,  196,  194,  193,  192,
      191,  190,  189,  181,  179,  178,  177,  176,  175,  174,

      173,  172,  171,  159,  156,  152,  149,  148,  147,  146,
      145,  144,  140,  138,  137,  136,  134,  132,  131,  130,
      128,  127,  126,  124,  123,  121,  120,  119,  118,  117,
      115,  114,  113,  112,  111,  110,  109,  108,  107,  106,
      102,  100,   98,   90,   84,   83,   82,   81,   80,   77,
       72,   69,   67,   66,   59,   58,   55,   51,   49,   42,
       38,   37,   36,   34,   33,   31,   28,   21,   14,    7,
        5,  491,  491,  491,  491,  491,  491,  491,  491,  491,
      491,  491,  491,  491,  491,  491,  491,  491,  491,  491,
      491,  491,  491,  491,  491,  491,  491,  491,  491,  491,

      491,  491,  491,  491,  491,  491,  491,  491,  491,  491,
      491,  491,  491,  491,  491,  491,  491,  491,  491,  491,
      491,  491,  491,  491,  491,  491,  491,  491,  491,  491,
      491,  491,  491,  491,  491,  491,  491,  491,  491,  491,
      491
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "k0lex.l"
/* -*-bison-*- */
/* Scanner for subset of Kotlin language "k0" */
#define YY_NO_INPUT 1
#line 7 "k0lex.l"
    #include "k0gram.tab.h"
    #include "symtab.h"
    int alctoken(int category);
    char *consume_sval(int str_type);
    extern char *filename;
    extern int exit_status; // overall exit status of main. Will be set to 1 in this file if there are any errors
    int lineno = 1; // keep track of line number 
    int multi_line_start; // keep track of when a multi line comment begins to give error if it is unclosed
#line 766 "lex.yy.c"

/* RULES */
#line 769 "lex.yy.c"

#define INITIAL 0
#define COMMENT 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 31 "k0lex.l"

#line 33 "k0lex.l"
 /* COMMENT state for multi-line comments */ 
#line 989 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 492 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 572 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 34 "k0lex.l"
{ BEGIN(COMMENT); multi_line_start = lineno; } /* switch to comment state where nothing will be counted */
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 35 "k0lex.l"
{BEGIN(INITIAL); } /* switch back to initial flex state */
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 36 "k0lex.l"
{}
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 37 "k0lex.l"
{lineno++;}
	YY_BREAK
case YY_STATE_EOF(COMMENT):
#line 38 "k0lex.l"
{return alctoken(UNCLOSED_COMMENT);}
	YY_BREAK
/* Initial state */
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 41 "k0lex.l"
{ lineno++; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 42 "k0lex.l"
{}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 43 "k0lex.l"
{}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 44 "k0lex.l"
{}   
	YY_BREAK
/* K0 Reserved Keywords */
case 9:
YY_RULE_SETUP
#line 48 "k0lex.l"
{ return alctoken(BREAK); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 49 "k0lex.l"
{ return alctoken(CONTINUE); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 50 "k0lex.l"
{ return alctoken(DO); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 51 "k0lex.l"
{ return alctoken(ELSE); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 52 "k0lex.l"
{ return alctoken(K_FALSE); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 53 "k0lex.l"
{ return alctoken(FOR); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 54 "k0lex.l"
{ return alctoken(FUN); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 55 "k0lex.l"
{ return alctoken(IF); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 56 "k0lex.l"
{ return alctoken(IN); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 57 "k0lex.l"
{ return alctoken(K_NULL); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 58 "k0lex.l"
{ return alctoken(RETURN); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 59 "k0lex.l"
{ return alctoken(K_TRUE); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 60 "k0lex.l"
{ return alctoken(VAL); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 61 "k0lex.l"
{ return alctoken(VAR); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 62 "k0lex.l"
{ return alctoken(WHEN); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 63 "k0lex.l"
{ return alctoken(WHILE); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 64 "k0lex.l"
{ return alctoken(IMPORT); }
	YY_BREAK
/* Kotline Reserved Keywords that we are not dealing with, return KEYWORD_ERROR */
case 26:
YY_RULE_SETUP
#line 67 "k0lex.l"
{ return alctoken(KEYWORD_ERROR); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 68 "k0lex.l"
{ return alctoken(KEYWORD_ERROR); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 69 "k0lex.l"
{ return alctoken(KEYWORD_ERROR); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 70 "k0lex.l"
{ return alctoken(KEYWORD_ERROR); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 71 "k0lex.l"
{ return alctoken(KEYWORD_ERROR); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 72 "k0lex.l"
{ return alctoken(KEYWORD_ERROR); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 73 "k0lex.l"
{ return alctoken(KEYWORD_ERROR); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 74 "k0lex.l"
{ return alctoken(KEYWORD_ERROR); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 75 "k0lex.l"
{ return alctoken(KEYWORD_ERROR); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 76 "k0lex.l"
{ return alctoken(KEYWORD_ERROR); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 77 "k0lex.l"
{ return alctoken(KEYWORD_ERROR); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 78 "k0lex.l"
{ return alctoken(KEYWORD_ERROR); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 79 "k0lex.l"
{ return alctoken(KEYWORD_ERROR); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 80 "k0lex.l"
{ return alctoken(KEYWORD_ERROR); }
	YY_BREAK
/* Soft keywords that we are not dealing with */
case 40:
YY_RULE_SETUP
#line 82 "k0lex.l"
{ return alctoken(KEYWORD_ERROR); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 83 "k0lex.l"
{ return alctoken(KEYWORD_ERROR); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 84 "k0lex.l"
{ return alctoken(KEYWORD_ERROR); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 85 "k0lex.l"
{ return alctoken(KEYWORD_ERROR); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 86 "k0lex.l"
{ return alctoken(KEYWORD_ERROR); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 87 "k0lex.l"
{ return alctoken(KEYWORD_ERROR); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 88 "k0lex.l"
{ return alctoken(KEYWORD_ERROR); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 89 "k0lex.l"
{ return alctoken(KEYWORD_ERROR); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 90 "k0lex.l"
{ return alctoken(KEYWORD_ERROR); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 91 "k0lex.l"
{ return alctoken(KEYWORD_ERROR); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 92 "k0lex.l"
{ return alctoken(KEYWORD_ERROR); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 93 "k0lex.l"
{ return alctoken(KEYWORD_ERROR); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 94 "k0lex.l"
{ return alctoken(KEYWORD_ERROR); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 95 "k0lex.l"
{ return alctoken(KEYWORD_ERROR); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 96 "k0lex.l"
{ return alctoken(KEYWORD_ERROR); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 97 "k0lex.l"
{ return alctoken(KEYWORD_ERROR); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 98 "k0lex.l"
{ return alctoken(KEYWORD_ERROR); }
	YY_BREAK
/* Kotlin modifier keywords not in k0 */
case 57:
YY_RULE_SETUP
#line 100 "k0lex.l"
{ return alctoken(KEYWORD_ERROR); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 101 "k0lex.l"
{ return alctoken(KEYWORD_ERROR); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 102 "k0lex.l"
{ return alctoken(KEYWORD_ERROR); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 103 "k0lex.l"
{ return alctoken(KEYWORD_ERROR); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 104 "k0lex.l"
{ return alctoken(KEYWORD_ERROR); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 105 "k0lex.l"
{ return alctoken(KEYWORD_ERROR); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 106 "k0lex.l"
{ return alctoken(KEYWORD_ERROR); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 107 "k0lex.l"
{ return alctoken(KEYWORD_ERROR); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 108 "k0lex.l"
{ return alctoken(KEYWORD_ERROR); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 109 "k0lex.l"
{ return alctoken(KEYWORD_ERROR); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 110 "k0lex.l"
{ return alctoken(KEYWORD_ERROR); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 111 "k0lex.l"
{ return alctoken(KEYWORD_ERROR); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 112 "k0lex.l"
{ return alctoken(KEYWORD_ERROR); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 113 "k0lex.l"
{ return alctoken(KEYWORD_ERROR); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 114 "k0lex.l"
{ return alctoken(KEYWORD_ERROR); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 115 "k0lex.l"
{ return alctoken(KEYWORD_ERROR); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 116 "k0lex.l"
{ return alctoken(KEYWORD_ERROR); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 117 "k0lex.l"
{ return alctoken(KEYWORD_ERROR); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 118 "k0lex.l"
{ return alctoken(KEYWORD_ERROR); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 119 "k0lex.l"
{ return alctoken(KEYWORD_ERROR); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 120 "k0lex.l"
{ return alctoken(KEYWORD_ERROR); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 121 "k0lex.l"
{ return alctoken(KEYWORD_ERROR); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 122 "k0lex.l"
{ return alctoken(KEYWORD_ERROR); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 123 "k0lex.l"
{ return alctoken(KEYWORD_ERROR); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 124 "k0lex.l"
{ return alctoken(KEYWORD_ERROR); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 125 "k0lex.l"
{ return alctoken(KEYWORD_ERROR); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 126 "k0lex.l"
{ return alctoken(KEYWORD_ERROR); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 127 "k0lex.l"
{ return alctoken(KEYWORD_ERROR); }
	YY_BREAK
/* Operators */
case 85:
YY_RULE_SETUP
#line 131 "k0lex.l"
{ return alctoken(INC); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 132 "k0lex.l"
{ return alctoken(DEC); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 133 "k0lex.l"
{ return alctoken(REQ); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 134 "k0lex.l"
{ return alctoken(RNEQ); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 135 "k0lex.l"
{ return alctoken(GTE); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 136 "k0lex.l"
{ return alctoken(LTE); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 137 "k0lex.l"
{ return alctoken(EQ); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 138 "k0lex.l"
{ return alctoken(NEQ); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 139 "k0lex.l"
{ return alctoken(AND); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 140 "k0lex.l"
{ return alctoken(OR); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 141 "k0lex.l"
{ return alctoken(NN_ASSERT); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 142 "k0lex.l"
{ return alctoken(SAFE_CALL); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 143 "k0lex.l"
{ return alctoken(ELVIS); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 144 "k0lex.l"
{ return alctoken(NULLABLE); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 145 "k0lex.l"
{ return alctoken(RANGE_EXCL); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 146 "k0lex.l"
{ return alctoken(RANGE_INCL); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 147 "k0lex.l"
{ return alctoken(PLUS_ASSIGN); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 148 "k0lex.l"
{ return alctoken(MINUS_ASSIGN); }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 149 "k0lex.l"
{ return alctoken(PLUS); }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 150 "k0lex.l"
{ return alctoken(MINUS); }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 151 "k0lex.l"
{ return alctoken(MUL); }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 152 "k0lex.l"
{ return alctoken(DIV); }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 153 "k0lex.l"
{ return alctoken(MOD); }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 154 "k0lex.l"
{ return alctoken(ASSIGN); }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 155 "k0lex.l"
{ return alctoken(GT); }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 156 "k0lex.l"
{ return alctoken(LT); }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 157 "k0lex.l"
{ return alctoken(NOT); }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 158 "k0lex.l"
{ return alctoken(DOT); }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 159 "k0lex.l"
{ return alctoken(TYPE_CAST); }
	YY_BREAK
/* Operators that produce OP_ERROR */
case 114:
YY_RULE_SETUP
#line 161 "k0lex.l"
{ return alctoken(OP_ERROR); }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 162 "k0lex.l"
{ return alctoken(OP_ERROR); }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 163 "k0lex.l"
{ return alctoken(OP_ERROR); }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 164 "k0lex.l"
{ return alctoken(OP_ERROR); }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 165 "k0lex.l"
{ return alctoken(OP_ERROR); }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 166 "k0lex.l"
{ return alctoken(OP_ERROR); }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 167 "k0lex.l"
{ return alctoken(OP_ERROR); }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 168 "k0lex.l"
{ return alctoken(OP_ERROR); }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 169 "k0lex.l"
{ return alctoken(OP_ERROR); }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 170 "k0lex.l"
{ return alctoken(OP_ERROR); }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 171 "k0lex.l"
{ return alctoken(OP_ERROR); }
	YY_BREAK
/* Punctuation */
case 125:
YY_RULE_SETUP
#line 175 "k0lex.l"
{ return alctoken(LPAREN); }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 176 "k0lex.l"
{ return alctoken(RPAREN); }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 177 "k0lex.l"
{ return alctoken(COMMA); }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 178 "k0lex.l"
{ return alctoken(SEMICOLON); }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 179 "k0lex.l"
{ return alctoken(LBRACE); }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 180 "k0lex.l"
{ return alctoken(RBRACE); }
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 181 "k0lex.l"
{ return alctoken(COLON); }
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 182 "k0lex.l"
{ return alctoken(LSQUARE); }
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 183 "k0lex.l"
{ return alctoken(RSQUARE); }
	YY_BREAK
/* Types */
case 134:
YY_RULE_SETUP
#line 186 "k0lex.l"
{ return alctoken(BYTE_TYPE); }
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 187 "k0lex.l"
{ return alctoken(SHORT_TYPE); }
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 188 "k0lex.l"
{ return alctoken(INT_TYPE); }
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 189 "k0lex.l"
{ return alctoken(LONG_TYPE); }
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 190 "k0lex.l"
{ return alctoken(FLOAT_TYPE); }
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 191 "k0lex.l"
{ return alctoken(DOUBLE_TYPE); }
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 192 "k0lex.l"
{ return alctoken(BOOLEAN_TYPE); }
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 193 "k0lex.l"
{ return alctoken(STRING_TYPE); }
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 194 "k0lex.l"
{ return alctoken(CHAR_TYPE); }
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 195 "k0lex.l"
{ return alctoken(ARRAY); }
	YY_BREAK
/* Literals */
case 144:
/* rule 144 can match eol */
YY_RULE_SETUP
#line 198 "k0lex.l"
{ return alctoken(CHAR); }
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 199 "k0lex.l"
{ return alctoken(INT); }
	YY_BREAK
case 146:
YY_RULE_SETUP
#line 200 "k0lex.l"
{ return alctoken(REAL); }
	YY_BREAK
case 147:
YY_RULE_SETUP
#line 201 "k0lex.l"
{ return alctoken(STRING); }
	YY_BREAK
case 148:
/* rule 148 can match eol */
YY_RULE_SETUP
#line 202 "k0lex.l"
{ return alctoken(MULTI_STRING); }
	YY_BREAK
/* identifier catchall */
case 149:
YY_RULE_SETUP
#line 205 "k0lex.l"
{ return alctoken(IDENT); }
	YY_BREAK
case 150:
YY_RULE_SETUP
#line 206 "k0lex.l"
{ return alctoken(ILL_IDENT);}
	YY_BREAK
/* Could not match */
case 151:
YY_RULE_SETUP
#line 209 "k0lex.l"
{ return alctoken(COULD_NOT_MATCH); }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 211 "k0lex.l"
{
    return alctoken(0);
}
	YY_BREAK
case 152:
YY_RULE_SETUP
#line 214 "k0lex.l"
ECHO;
	YY_BREAK
#line 1832 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 492 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 492 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 491);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 214 "k0lex.l"


int alctoken(int category)
{
    struct tree *t = malloc(sizeof(struct tree));
    if (t == NULL) {
        fprintf(stderr, "Failed to allocate memory for tree node\n");
        exit(1);
    }

    // initialize kids
    for (int i = 0; i < 10; i++) {
        t->kids[i] = NULL;
    }

    t->id = serial++;
    t->prodrule = category;
    t->symbolname = NULL;
    t->nkids = 0;

    t->type = NULL; // not needed for leaf typing
    

    t->leaf = malloc(sizeof(struct token));
    if (t->leaf == NULL) {
        fprintf(stderr, "Failed to allocate memory for token\n");
        exit(1);
    }

    // malloc the type pointer for this token
    t->leaf->type = malloc(sizeof(*(t->leaf->type)));
    memset(t->leaf->type, 0, sizeof(*(t->leaf->type)));

    switch (category)
    {
        case KEYWORD_ERROR:
            fprintf(stderr, "%s:%d: scanner error: Kotlin reserved keyword: \"%s\" is not a part of k0\n",
                   filename, lineno, yytext);
            exit_status = 1;
            break;

        case UNCLOSED_COMMENT:
            fprintf(stderr, "%s:%d: scanner error: unclosed multi-line comment\n",
                   filename, multi_line_start);
            exit_status = 1;
            break;

        case COULD_NOT_MATCH:
            fprintf(stderr, "%s:%d: scanner error: \'%s\' could not be matched\n",
                   filename, lineno, yytext);
            exit_status = 1;
            break;

        case ILL_IDENT:
            fprintf(stderr, "%s:%d: scanner error: \'%s\' is an illegal identifier\n",
                   filename, lineno, yytext);
            exit_status = 1;
            break;

        case OP_ERROR:
            fprintf(stderr, "%s:%d: scanner error: \'%s\' is an illegal operator\n",
                   filename, lineno, yytext);
            exit_status = 1;
            break;

        default:
            break;
    }

    // fill token fields
    t->leaf->category = category;
    t->leaf->text = strdup(yytext);
    t->leaf->lineno = lineno;
    t->leaf->filename = strdup(filename);

    t->leaf->ival = 0;
    t->leaf->dval = 0.0;
    t->leaf->sval = NULL;

    switch (category)
    {
        case INT:
            t->leaf->ival = atoi(yytext);
            t->leaf->type->basetype = INT_TYPE;
            break;

        case REAL:
            t->leaf->dval = atof(yytext);
            t->leaf->type->basetype = DOUBLE_TYPE;
            break;

        case STRING:
        case MULTI_STRING:
            t->leaf->sval = consume_sval(category);
            if (t->leaf->sval == NULL) {
                fprintf(stderr, "%s:%d: scanner error: unsupported escape sequence in %s\n",
                       filename, lineno, yytext);
                exit_status = 1;
            }
            t->leaf->type->basetype = STRING_TYPE;
            break;
        case CHAR:
            t->leaf->type->basetype = CHAR_TYPE;
            break;
        case K_FALSE:
        case K_TRUE:
            t->leaf->type->basetype = BOOLEAN_TYPE;
            break;

    }

    yylval.treeptr = t;
    return category;
}

char *consume_sval(int str_type)
{
    // allocate worst-case size (raw string length including escapes and quotes)
    char *tmp = (char *)malloc(yyleng + 1);
    char *start = tmp;

    // pointer to iterate over the raw lexer text
    char *raw_text = yytext + 1;     // skip initial quote
    char *end = yytext + yyleng - 1; // stop before final quote

    if (str_type == MULTI_STRING)
    {
        raw_text = yytext + 3;
        end = yytext + yyleng - 3;
    }

    // iterate through raw text, consuming escapes and copying characters
    while (raw_text < end)
    {
        // encountered a backslash, meaning an escape sequence
        if (*raw_text == '\\')
        {
            raw_text++; // move to escaped character

            // check what the escaped character is
            switch (*raw_text)
            {
            case 'n': // consume newline
                *tmp = '\n';
                break;
            case 't': // consume tab
                *tmp = '\t';
                break;
            case '\\': // consume literal backslash
                *tmp = '\\';
                break;
            case '\'': // consume apostrophe
                *tmp = '\'';
                break;
            case '\"': // consume quote
                *tmp = '\"';
                break;
            case 'r': // consume carriage return
                *tmp = '\r';
                break;
            case 'b': // consume backspace
                *tmp = '\b';
                break;
            default:
                // unsupported escape sequence
                free(start);
                return NULL;
            }
        }
        else
        {
            // regular character, copy as-is
            *tmp = *raw_text;
        }

        tmp++;
        raw_text++;
    }

    // null-terminate the final string value
    *tmp = '\0';

    return start;
}
